ryz310/my_api_client

lib/my_api_client/errors.rb, lib/my_api_client/params/params.rb, lib/my_api_client/params/request.rb, spec/lib/my_api_client/errors/error_spec.rb, spec/lib/my_api_client/params/params_spec.rb, spec/lib/my_api_client/params/request_spec.rb
Added #to_bugsnag method to `MyApiClient::Params::Params`. 
It makes easier to send metadata to bugsnag.
```rb
begin
api_client = SomeApiClient.new.request
rescue MyApiClient::Error => e
Bugsnag.notify(e, e.to_bugsnag)
end
```
I want to support Bugsnag::Breadcrumbs in the future.
See: https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.11.0
=> Support bugsnag metadata

lib/my_api_client.rb
I could not execute `$ bin/console` because some requirements were missed.
=> Add requirements for `$ bin/console`

.circleci/config.yml, .rubocop.yml, Gemfile, Gemfile.lock, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile, gemfiles/rails_5.2.gemfile, lib/my_api_client.rb, lib/my_api_client/errors.rb, lib/my_api_client/integrations/bugsnag.rb, lib/my_api_client/params/params.rb, lib/my_api_client/params/request.rb, lib/my_api_client/rspec/stub.rb, spec/lib/my_api_client/error_handling_spec.rb, spec/lib/my_api_client/errors/error_spec.rb, spec/lib/my_api_client/errors/network_error_spec.rb, spec/lib/my_api_client/integrations/bugsnag_spec.rb, spec/lib/my_api_client/params/params_spec.rb, spec/lib/my_api_client/params/request_spec.rb, spec/lib/my_api_client/request_spec.rb, spec/lib/my_api_client/rspec/stub_spec.rb
closes #23
> [Bugsnag-Ruby v6.11.0](https://github.com/bugsnag/bugsnag-ruby/releases/tag/v6.11.0) was Added new feature whic called logging breadcrumbs.
> I want to support that feature in this gem.
> 
> See: https://docs.bugsnag.com/platforms/ruby/other/#logging-breadcrumbs
> 
> refs: #22
=> Support bugsnag breadcrumb

lib/my_api_client/integrations/bugsnag.rb, spec/lib/my_api_client/integrations/bugsnag_spec.rb
The feature of Bugsnag breadcrumbs supports only following data.
> https://docs.bugsnag.com/platforms/ruby/rails/#logging-breadcrumbs
> The breadcrumb name will be trimmed to be 30 characters maximum, and all meta data must be of the **Numeric, String, TrueClass, or FalseClass types, or nil**.
But the `MyApiClient::Error#metadata` includes the Array, Hash and so on.
https://github.com/ryz310/my_api_client/blob/03182c9577e632ae5f30786efe0876de6ead00d1/lib/my_api_client/integrations/bugsnag.rb#L12-L16
So unfortunately, some metadata has excluded from breadcrumbs.
The workaround is to convert metadata into strings.
=> Fix unsupported data for the Bugsnag breadcrumbs

lib/my_api_client/request.rb, spec/lib/my_api_client/request_spec.rb
fixes #53
> The log `GET http:/v3.3/me/friends` is wrong URL. It is not considering schema and domain name.
> 
> ```
> I, [2019-06-19T15:12:33.753081 #58]  INFO -- : API request `GET http:/v3.3/me/friends`: "Start"
> I, [2019-06-19T15:12:34.225469 #58]  INFO -- : API request `GET http:/v3.3/me/friends`: "Duration 0.4365701 sec"
> I, [2019-06-19T15:12:34.260660 #58]  INFO -- : API request `GET http:/v3.3/me/friends`: "Success (200)"
> ```
> 
> The reason is that the Faraday instance is initialized by Sawyer::Agent#initialize but it has not yet been called at timing of Logger instance initialization.
> 
> https://github.com/ryz310/my_api_client/blob/38c4130970fdf013326d1b46cc7b56602dadd809/lib/my_api_client/request.rb#L16-L21
=> Initialize sawyer agent before logger initialization

lib/my_api_client/rspec/matchers/be_handled_as_an_error.rb
Currently, calling `be_handled_as_an_error` matcher without an error class displays as following:
```
is expected not to be handled as
```
This PR fixes it, and then displays as following:
```
is expected not to be handled as an error
```
=> Fix `be_handled_as_an_error` description

lib/my_api_client/rspec/matchers/be_handled_as_an_error.rb, lib/my_api_client/rspec/matchers/request_to.rb
=> Ignore error handling when using request to matcher

Gemfile.lock, lib/my_api_client/errors.rb, my_api_client.gemspec
The faraday gem error class definitions were updated by [v0.17.1](https://github.com/lostisland/faraday/pull/1082) and then some error class' super classes were changed.
Originally, any network error classes had inherited `Faraday::ClientError` class, but currently have inherited `Faraday::ServerError` or `Faraday::Error` class.
The `my_api_client` gem needs redefine the network error class and to add dependency by the faraday gem version.
=> Redefine network error class

lib/my_api_client/error_handling.rb, lib/my_api_client/error_handling/generator.rb, lib/my_api_client/rspec/stub.rb, lib/my_api_client/service_abstract.rb, my_api_client.gemspec
Fixed: `warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call`
=> Fix warning on ruby 2.7

README.jp.md, lib/my_api_client/rspec/stub.rb, spec/lib/my_api_client/rspec/stub_spec.rb
Allow to use the `response` option with the `raise` option.
So you can stub a response on raising error.
```ruby
stub_api_client_all(
ExampleApiClient,
request: {
raise: MyApiClient::Error,
response: { message: 'error' }
}
)
begin
ExampleApiClient.new.request(user_id: 1)
rescue MyApiClient::Error => e
response_body = e.params.response.data.to_h
expect(response_body).to eq(message: 'error')
end
```
=> Stub response on raising error

lib/my_api_client/base.rb, lib/my_api_client/config.rb, lib/my_api_client/logger.rb, lib/my_api_client/params/request.rb, lib/my_api_client/request.rb, spec/dummy_app/api_clients/example_api_client.rb, spec/lib/my_api_client/base_spec.rb, spec/lib/my_api_client/config_spec.rb, spec/lib/my_api_client/logger_spec.rb, spec/lib/my_api_client/params/request_spec.rb, spec/lib/my_api_client/request_spec.rb
**before**
```
I, [2020-02-02T15:26:53.788092 #93220]  INFO -- : API request `GET https://api.esa.io/v1/teams/feedforce/posts`: "Start"
I, [2020-02-02T15:26:55.760452 #93220]  INFO -- : API request `GET https://api.esa.io/v1/teams/feedforce/posts`: "Duration 1.97186 sec"
I, [2020-02-02T15:26:55.760739 #93220]  INFO -- : API request `GET https://api.esa.io/v1/teams/feedforce/posts`: "Success (200)"
```
**after**
Shows URL with query strings.
```
I, [2020-02-02T15:20:47.471040 #90870]  INFO -- : API request `GET https://api.esa.io/v1/teams/feedforce/posts?page=1&per_page=100&q=user%3Aryosuke_sato+category%3Aunsorted`: "Start"
I, [2020-02-02T15:20:49.516099 #90870]  INFO -- : API request `GET https://api.esa.io/v1/teams/feedforce/posts?page=1&per_page=100&q=user%3Aryosuke_sato+category%3Aunso …
```
=> Change the request structure

README.jp.md, lib/my_api_client/error_handling.rb, lib/my_api_client/error_handling/generator.rb, spec/lib/my_api_client/error_handling/generator_spec.rb
Until now, using "with" or "block" in "error_handling" did not automatically raise an exception, but will now always raise an exception when an error is detected.
**Before**
```rb
error_handling json: { '$.errors.code': 10..19 }, with: :my_error_handling
def my_error_handling
end
```
```rb
error_handling status_code: 500..599 do |_params, logger|
end
```
**After**
```rb
error_handling json: { '$.errors.code': 10..19 }, with: :my_error_handling
def my_error_handling
end
```
```rb
error_handling status_code: 500..599 do |params, logger|
end
```
=> Raise an exception whenever an error is detected

.circleci/config.yml, example/api_clients/my_rest_api_client.rb, lib/my_api_client/request.rb, lib/my_api_client/request/basic.rb, my_api/spec/controllers/rest_controller_spec.rb, spec/example/api_clients/my_rest_api_client_spec.rb, spec/integrations/api_clients/my_rest_api_client_spec.rb
Currently, this gem does not support HTTP PUT method correctly.
There is `MyApiClient::Request::Basic#put` method but it calls HTTP `PATCH` method, because the `#put` method is alias of `#patch` method.
https://github.com/ryz310/my_api_client/blob/ea0e4a7272b318d0f5ea32e723f40c9180e53dae/lib/my_api_client/request/basic.rb#L31
Today, I've encountered an endpoint which accepts only HTTP `PUT` method, and I found that this API client can't call the API, so I fixed this implementation.
=> Support HTTP PUT method

README.jp.md, lib/my_api_client/rspec/stub.rb, spec/integrations/api_clients/my_error_api_client_spec.rb, spec/integrations/api_clients/my_pagination_api_client_spec.rb, spec/integrations/api_clients/my_rest_api_client_spec.rb, spec/integrations/api_clients/my_status_api_client_spec.rb, spec/lib/my_api_client/rspec/stub_spec.rb
Add `pageable` option to `#stub_api_client`:
```rb
stub_api_client(
MyPaginationApiClient,
pagination: {
pageable: [
{ page: 1 },
{ page: 2 },
{ page: 3 },
],
}
)
MyPaginationApiClient.new.pagination.each do |response|
response.page #=> 1, 2, 3
end
```
=> Stubbed pagination

README.jp.md, lib/my_api_client/rspec/stub.rb, spec/lib/my_api_client/rspec/stub_spec.rb
Resolve #563
Add new feature for stubbing status code on testing.
You can use it as following:
```ruby
stub_api_client_all(
ExampleApiClient,
request: {
raise: MyApiClient::Error,
response: { message: 'error' },
status_code: 429
}
)
begin
ExampleApiClient.new.request(user_id: 1)
rescue MyApiClient::Error => e
status_code = e.params.response.status
expect(status_code).to eq(429)
end
```
=> Stubbing status code on testing

README.jp.md, README.md, example/api_clients/my_errors.rb, example/api_clients/my_header_api_client.rb, lib/my_api_client/error_handling/generator.rb, my_api/app/controllers/header_controller.rb, my_api/config/routes.rb, my_api/spec/controllers/header_controller_spec.rb, spec/example/api_clients/my_header_api_client_spec.rb, spec/integrations/api_clients/my_header_api_client_spec.rb, spec/lib/my_api_client/error_handling/generator_spec.rb
resolves #789
To make it support the header error handling for `error_handling`.
For example
```
error_handling headers: { 'www-authenticate': /invalid token/ }, with: :my_error_handling
```
=> Support response header error handling

lib/generators/generator_helper.rb
`my_api_client` generator does not work on Rails7.
> $ rails g api_client path/to/resource get:path/to/resource --endpoint https://example.com/
> Running via Spring preloader in process 90
> /usr/local/bundle/ruby/3.0.0/gems/railties-7.0.4/lib/rails/generators/named_base.rb:130:in `route_url': undefined local variable or method `controller_class_path' for #<Rails::ApiClientGenerator:0x0000ffff751ae238 @inside_template=nil, @behavior=:invoke, @_invocations={Rails::ApiClientGenerator=>["check_class_collision", "generate_root_class", "generate_api_client"]}, @_initializer=[["path/to/resource", "get:path/to/resource"], ["--endpoint", "https://example.com/"], {:behavior=>:invoke, :destination_root=>#<Pathname:/app>, :shell=>#<Thor::Shell::Color:0x0000ffff751ae4b8 …
=> Fix error that generating api client failed on Rails 7

example/api_clients/my_pagination_api_client.rb, lib/my_api_client/request/pagination.rb, lib/my_api_client/rspec/stub.rb, spec/example/api_clients/my_pagination_api_client_spec.rb, spec/integrations/api_clients/my_pagination_api_client_spec.rb, spec/lib/my_api_client/request/pagination_spec.rb
This Pull Request introduces an enhancement to the `#pageable_get` method in our Ruby library. It enables the use of a `Proc` object for the `paging` option, allowing more dynamic and flexible generation of request URLs based on the response body.
Previously, the `paging` option in the `#pageable_get` method was limited to specifying URLs using JSONPath. This approach was effective but had a limitation: it could not handle cases where the URL provided in the response body was not a full path. This limitation could hinder the method's utility in scenarios where the API responses include relative URLs or require more complex URL construction based on the response.
The proposed change allows the `paging` option to accept a `Proc` object. This enhancement provides the following benefits:
1. …
=> Enable Dynamic URL Generation for `#pageable_get` via `Proc` Objects

lib/my_api_client/exceptions.rb, spec/lib/my_api_client/exceptions_spec.rb
This gem utilizes retry_on with ActiveSupport::Rescuable for implementation, but the behavior of `ActiveSupport::Rescuable.rescue_with_handler` has changed since ActiveSupport v5.2.
Since ActiveSupport 5.2, if no handler exists for the exception passed as an argument, it searches for a handler attached to the `#cause` of that exception.
https://github.com/rails/rails/blob/v5.2.0/activesupport/lib/active_support/rescuable.rb#L88-L101
Therefore, even when the exception changes after being retried due to a retryable exception, 
it continues to be processed as a retryable exception because it searches for a handler attached to the `#cause` of the exception.
e.g.
```rb
class Example
class RetriableError < StandardError; end
class OtherError < StandardError; end
include MyApiClient::Exceptions …
```
=>  Fix handling when the error changes after a retry

lib/my_api_client/params/request.rb, lib/my_api_client/request.rb, lib/my_api_client/request/basic.rb, lib/my_api_client/request/pagination.rb, spec/lib/my_api_client/params/request_spec.rb
The API client allows lazy evaluation for request headers and body parameters.
For example, a time-limited token can be issued immediately before the request.
```rb
class ExampleApiClient < MyApiClient::Base
def get_users
get 'users', headers: headers, query: { key: 'value' }
end
private
def headers
lambda do
new_access_token = issue_new_access_token!
{
'Content-Type': 'application/json;charset=UTF-8',
'Authorization': "Bearer #{new_access_token}",
}
end
end
end
=> Support lazy evaluation for request headers and body parameters

.circleci/config.yml
This gem has been tested with real API requests using a test API created by Ruby on Jets.
Unfortunately, I don't maintain the jets update for a long time, and then the testing API spec is broken.
---
My motivation for using Ruby on Jets is to keep server cost low by using AWS Lambda and API Gateway, etc.
On the other hand, even Ruby on Rails v8.0 has established a way to create a cheap server.
So, I may recreate the testing API with Ruby on Rails.
=> Stop CI for the testing API test
