ryz310/my_api_client

Gemfile.lock
README.jp.md
README.md
lib/generators/rails/templates/api_client.rb.erb
lib/generators/rspec/templates/api_client_spec.rb.erb
lib/my_api_client/version.rb

Release v0.1.1

---

Gemfile.lock
lib/generators/rails/templates/api_client.rb.erb
lib/generators/rspec/templates/api_client_spec.rb.erb
lib/my_api_client/version.rb

Release v0.1.3

---

.circleci/config.yml

* Fix problem on the release job.
* Modify caching key
* Refactoring

Fix problem on the release job

---

.rubocop.yml
README.jp.md
lib/my_api_client/rspec.rb
lib/my_api_client/rspec/stub.rb
spec/lib/my_api_client/rspec/stub_spec.rb

Provide test helper for RSpec.
See README.jp.md for detail.

Test helper for RSpec

---

.circleci/config.yml

* [CircleCI Orb Registry \- sue445/ruby\-orbs](https://circleci.com/orbs/registry/orb/sue445/ruby-orbs)
* [CircleCI Orb Registry \- rvla/code\-climate](https://circleci.com/orbs/registry/orb/rvla/code-climate)

Use CircleCI Orbs

---

.circleci/config.yml
Gemfile.lock
README.jp.md
lib/my_api_client/integrations/bugsnag.rb
lib/my_api_client/version.rb
spec/lib/my_api_client/integrations/bugsnag_spec.rb

* Fix unsupported data for the Bugsnag breadcrumbs (#50)

Release v0.5.1

---

.circleci/config.yml

Support parallel testing.
**Documents**
* [Configuring Test Coverage](https://docs.codeclimate.com/docs/configuring-test-coverage#section-parallel-tests)
**To be helpful**
* [error "Invalid path part "" on uploaded coverage · Issue \#375 · codeclimate/test\-reporter](https://github.com/codeclimate/test-reporter/issues/375)

Improvement test coverage

---

lib/my_api_client/exceptions.rb
spec/lib/my_api_client/exceptions_spec.rb

Fix the result of the retry

---

lib/my_api_client/error_handling.rb
spec/lib/my_api_client/error_handling_spec.rb

The gem had raised parsing error if request to text/html content. This PR fix it.

Fix parsing error if given text/html response

---

lib/my_api_client/params/params.rb
spec/lib/my_api_client/params/params_spec.rb

Add request duration to metadata

---

lib/my_api_client/error_handling.rb
spec/lib/my_api_client/error_handling_spec.rb

Support boolean on error handling

---

Gemfile.lock
lib/my_api_client.rb
my_api_client.gemspec

It will include in my_api_client v0.8.0.

Require sawyer gem v0.8.2 over

---

.rubocop.yml
lib/my_api_client.rb
lib/my_api_client/exceptions.rb
lib/my_api_client/rspec/matchers/be_handled_as_an_error.rb
lib/my_api_client/service_abstract.rb
lib/my_api_client/sleeper.rb
spec/dummy_app/api_clients/example_api_client.rb
spec/integrations/api_clients/example_api_client_spec.rb
spec/lib/my_api_client/rspec/matchers/be_handled_as_an_error_spec.rb
spec/lib/my_api_client/sleeper_spec.rb
spec/spec_helper.rb
spec/support/complete_about.rb
spec/support/complete_within.rb

Avoid sleep on testing

---

.rubocop.yml
lib/my_api_client/error_handling/generator.rb
spec/integrations/api_clients/example_api_client_spec.rb
spec/lib/my_api_client/error_handling/generator_spec.rb
spec/lib/my_api_client/sleeper_spec.rb

Verify arguments on error handling definition

---

.dependabot/config.yml

See: https://dependabot.com/docs/config-file/

Add a config file of the dependabot

---

example/api_clients/application_api_client.rb
example/api_clients/my_errors.rb
example/api_clients/my_status_api_client.rb
my_api/README.md
my_api/app/controllers/status_controller.rb
my_api/config/routes.rb
my_api/spec/controllers/status_controller_spec.rb
spec/example/api_clients/my_status_api_client_spec.rb
spec/integrations/api_clients/my_status_api_client_spec.rb

Add status API

---

example/api_clients/my_error_api_client.rb
example/api_clients/my_errors.rb
example/api_clients/my_status_api_client.rb
my_api/README.md
my_api/app/controllers/error_controller.rb
my_api/config/routes.rb
my_api/spec/controllers/error_controller_spec.rb
spec/example/api_clients/my_error_api_client_spec.rb
spec/integrations/api_clients/my_error_api_client_spec.rb
spec/integrations/api_clients/my_rest_api_client_spec.rb
spec/integrations/api_clients/my_status_api_client_spec.rb
spec/spec_helper.rb

Add error API

---

lib/my_api_client/request/executor.rb
spec/lib/my_api_client/request/executor_spec.rb

Change the duration format to milliseconds

---

.circleci/config.yml
README.jp.md
lib/generators/rails/USAGE
lib/generators/rails/api_client_generator.rb
lib/generators/rails/templates/api_client.rb.erb
lib/generators/rspec/USAGE
lib/generators/rspec/api_client_generator.rb
lib/generators/rspec/templates/api_client_spec.rb.erb

Add `endpoint` option to the generator.
```sh
$ bin/rails g api_client path/to/resource get:path/to/resource --endpoint https://myapi.com
```

Add endpoint option to the generator

---

.circleci/config.yml

See: [Matrix jobs \- Matrix builds \| CircleCI](https://circleci.com/blog/circleci-matrix-jobs/)

Use Circle CI matrix

---

my_api/Gemfile
my_api/Gemfile.lock

To restrict dependency bump up by the dependabot, like as #782,  #783.

Pin the version of the jets gem
